### ISSUE TITLE
Shared Component build is broken.

### ISSUE THREAD

**Issue by kalyankondapally** [01org/ozone-wayland#328]
With latest master TOT, shared component build doesn't work. Need to fix this.

**Comment by kalyankondapally** [comment]
@rakuco So you think this should be resolved now ?

**Comment by rakuco** [comment]
There's still a problem with Chromium itself I've been discussing with the Chromium folks in #ozone-wayland on and off: `OzonePlatformWayland::CreateNativeDisplayDelegate()` refers to `NativeDisplayDelegateOzone`, which is not exported in `src/ui/ozone/common/native_display_delegate_ozone.h`.

For Crosswalk I've been exporting that class, but we need to consider whether we can just return `NULL`, copy that class locally or convince the Chromium people to move that file to `public`.

**Comment by kalyankondapally** [comment]
I think we can return null as we dont intend to use that here.

**Comment by rakuco** [comment]
Right; I'll try to do that tomorrow and see if the build works. If it does, I'll close this issue.

**Comment by rakuco** [comment]
It worked, as I've sent #358 to do this. However, as I mentioned in f5b3508f200892b0e1548071b390cc81104ece2a, that commit causes a regression, as it calls a symbol that's implemented in libozone.so and we cannot add a dependency on the `ozone` target in `wayland.gyp`.

**Comment by kalyankondapally** [comment]
Should be fixed now. Closing this.
